### ISSUE TITLE
Add support for Composition API

### ISSUE THREAD

**Issue by stalker3343** [andrewvasilchuk/vue-typed-emit#1]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

How use this plugin with `defineComponent` and `setup`?

![изображение](https://user-images.githubusercontent.com/42894422/98442794-01ea5c00-2118-11eb-98d2-ea127d0a052e.png)

I have an error in `methods` but not in `setup`

**Comment by andrewvasilchuk** [comment]
@stalker3343, Thanks for creating the issue. I will provide you with a solution today.

**Comment by andrewvasilchuk** [comment]
@stalker3343, Please check out the updated docs (Composition API) section.
