### ISSUE TITLE
Publish Composition Version on NPM

### ISSUE THREAD

**Issue by stalker3343** [andrewvasilchuk/vue-typed-emit#3]
### Describe the bug

I can't update the package because the old version is on npm

### Expected behavior
Version 1.1.0 on NPM

### Versions

**Libraries:**

- Vue: 2.#.#

https://www.npmjs.com/package/vue-typed-emit

**Comment by andrewvasilchuk** [comment]
@stalker3343, Sorry, I didn't expect you want it to be published so quickly 😅. `vue-typed-emit@1.1.0` is available on [NPM](https://www.npmjs.com/package/vue-typed-emit).
