### ISSUE TITLE
feat: extend type of `$root.$emit`

### ISSUE THREAD

**Issue by emorvillez** [andrewvasilchuk/vue-typed-emit#5]
Hi,

It seems not working for global emit on `$root.$emit`. Maybe it is not a big work to add that?

Regards

**Comment by andrewvasilchuk** [comment]
@emorvillez, thanks for a suggestion I will take a look.

**Comment by andrewvasilchuk** [comment]
@emorvillez It's possible. Do you have any suggestions regarding how it should be implemented? My suggestion is to add another type like `WithRootEvents<RootEvents>` which will enhance typing of `this.$root.$emit`? This will also add an ability to create an app specific utility type `WithAppRootEvents = WithRootEvents<{ foo: 'bar' }>`.

**Comment by andrewvasilchuk** [comment]
This project is not maintained anymore since Vue 3 has introduced a built in support for typing component events.
