### ISSUE TITLE
Can't use strings array as event type

### ISSUE THREAD

**Issue by d9k** [andrewvasilchuk/vue-typed-emit#6]
### Describe the bug

```ts
type EventsElementsSelector = {
  input: Array<string>;
};

export default  (Vue as WithEvents<EventsElementsSelector>).extend({
   onInput(newValue: Array<string>) {
      this.$emit('input', newValue);
    }
});
```

### Expected behavior

No type error.

### Actual behavior

Error: `Argument of type 'string[]' is not assignable to parameter of type 'string'.`

### Versions

- vue-typed-emit: 1.1.0

- Vue: 2.6.12

**Comment by d9k** [comment]
@andrewvasilchuk, do you have idea how to fix the issue?

**Comment by SKFrozenCloud** [comment]
string[] ?

**Comment by andrewvasilchuk** [comment]
@d9k, sorry for the late answer. For any array that is in the first place of `$emit` payload you should use the following syntax.

```ts
interface Events {
  input: [string[]]
}
```

**Comment by andrewvasilchuk** [comment]
@d9k, can we close the issue?

**Comment by andrewvasilchuk** [comment]
I have added a section in docs on how to address it.
