### ISSUE TITLE
Vue 3 - Types incompatibility 

### ISSUE THREAD

**Issue by IrvingArmenta** [andrewvasilchuk/vue-typed-emit#7]
### Describe the bug

Types incompatibility in Vue 3.
Got this message when applying the example code in SFC Composition API:

```
Interface 'ExtendedSetupContext' incorrectly extends interface 'SetupContext<EmitsOptions>'.
  Types of property 'emit' are incompatible.
```

This is how I setup the code, as the example:
```vue
<script lang="ts">
import { defineComponent, ref, PropType, SetupContext } from 'vue';
import { CompositionAPIEmit } from 'vue-typed-emit';

interface Events {
  foo: string;
  bar: [string, number];
  baz: undefined;
}

interface ExtendedSetupContext extends SetupContext {
  emit: CompositionAPIEmit<Events>;
}

// defineComponent and setup(props) call...
</script>
```
### Expected behavior

Emits are properly typed as expected

### Versions

**Libraries:**

```json
{
  "vue": "^3.0.0",
  "vue-typed-emit": "^1.1.0",
  "typescript": "^4.4.4"
}
 ```

**Comment by andrewvasilchuk** [comment]
@IrvingArmenta you don't need this library for Vue 3. Vue 3 provides [an ability to provide types of emits](https://vuejs.org/guide/typescript/composition-api.html#typing-component-emits).

**Comment by andrewvasilchuk** [comment]
This project is not maintained anymore since Vue 3 has introduced a built in support for typing component events.
